INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Centurion ERP
repo_url: https://gitlab.com/nofusscomputing/projects/centurion_erp
edit_uri: '/-/ide/project/nofusscomputing/projects/centurion_erp/edit/development/-/docs/'

plugins:
  mkdocstrings:
    enabled: true
    handlers:
      python:
        setup_commands:
          - import os
          - import django
          - os.chdir('app/')
          - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "app.settings")
          - django.setup()
        options:
          find_stubs_package: true
          heading_level: 2
          inherited_members: false
          members_order: source
          paths: [ '.' ]
          parameter_headings: false
          show_category_heading: true
          show_if_no_docstring: true
          show_labels: false
          show_object_full_path: false
          show_root_heading: false
          show_root_full_path: true
          show_root_toc_entry: false
          show_signature_annotations: false
          show_source: false
          show_submodules: true
          summary: true


nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Centurion ERP:

    - projects/centurion_erp/index.md

    - Administration:

      - projects/centurion_erp/administration/index.md

      - projects/centurion_erp/administration/authentication.md

      - projects/centurion_erp/administration/backup.md

      - projects/centurion_erp/administration/installation.md

    - Development:

      - projects/centurion_erp/development/index.md

      - Application API:

        - projects/centurion_erp/development/api/index.md

        - projects/centurion_erp/development/api/admin_model_form.md

        - projects/centurion_erp/development/api/model_form.md

        - projects/centurion_erp/development/api/token_authentication.md

        - Models:

          - projects/centurion_erp/development/api/models/index.md

          - projects/centurion_erp/development/api/models/core_history_save.md

          - projects/centurion_erp/development/api/models/itam_device.md

          - projects/centurion_erp/development/api/models/access_organization_permission_checking.md

          - projects/centurion_erp/development/api/models/tenancy_object.md

        - projects/centurion_erp/development/api/common_views.md

        - Serializers:

          - projects/centurion_erp/development/api/serializer/index.md

          - projects/centurion_erp/development/api/serializer/inventory.md

        - Unit Testing:

          - projects/centurion_erp/development/api/tests/index.md

          - projects/centurion_erp/development/api/tests/models.md

          - projects/centurion_erp/development/api/tests/model_history.md

          - projects/centurion_erp/development/api/tests/model_history_child_item.md

          - projects/centurion_erp/development/api/tests/model_history_parent_item.md

          - projects/centurion_erp/development/api/tests/model_history_permissions.md

          - projects/centurion_erp/development/api/tests/model_permissions.md

          - projects/centurion_erp/development/api/tests/model_permissions_organization_manager.md

          - projects/centurion_erp/development/api/tests/model_permission_add.md

          - projects/centurion_erp/development/api/tests/model_permission_add_organization_manager.md

          - projects/centurion_erp/development/api/tests/model_permission_change.md

          - projects/centurion_erp/development/api/tests/model_permission_change_organization_manager.md

          - projects/centurion_erp/development/api/tests/model_permission_delete.md

          - projects/centurion_erp/development/api/tests/model_permission_delete_organization_manager.md

          - projects/centurion_erp/development/api/tests/model_permission_view.md

          - projects/centurion_erp/development/api/tests/model_permission_view_organization_manager.md

          - projects/centurion_erp/development/api/tests/model_permissions_api.md

          - projects/centurion_erp/development/api/tests/model_permission_api_add.md

          - projects/centurion_erp/development/api/tests/model_permission_api_change.md

          - projects/centurion_erp/development/api/tests/model_permission_api_delete.md

          - projects/centurion_erp/development/api/tests/model_permission_api_view.md

          - projects/centurion_erp/development/api/tests/model_tenancy_object.md

          - projects/centurion_erp/development/api/tests/model_views.md

          - projects/centurion_erp/development/api/tests/notes_permissions.md

      - projects/centurion_erp/development/forms.md

      - projects/centurion_erp/development/models.md

      - projects/centurion_erp/development/testing.md

      - projects/centurion_erp/development/views.md
    
    - User:

      - projects/centurion_erp/user/index.md

      - projects/centurion_erp/user/user_settings.md

      - Access:

        - projects/centurion_erp/user/access/index.md

        - projects/centurion_erp/user/access/organization.md

        - projects/centurion_erp/user/access/team.md

      - projects/centurion_erp/user/configuration.md

      - projects/centurion_erp/user/api.md

      - projects/centurion_erp/user/config_management/index.md

      - Core:

        - projects/centurion_erp/user/core/index.md

      - ITAM:

        - projects/centurion_erp/user/itam/index.md

        - projects/centurion_erp/user/itam/device.md

        - projects/centurion_erp/user/itam/operating_system.md

        - projects/centurion_erp/user/itam/software.md

      - projects/centurion_erp/user/settings.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

