INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Django Template
repo_url: https://gitlab.com/nofusscomputing/infrastructure/configuration-management/django_app
edit_uri: '/-/ide/project/nofusscomputing/infrastructure/configuration-management/django_app/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Django Template:

    - projects/django-template/index.md

    - projects/django-template/api.md

    - projects/django-template/config_management/index.md

    - projects/django-template/permissions.md

    - Core:

      - projects/django-template/core/index.md

    - ITAM:

      - projects/django-template/itam/index.md

      - projects/django-template/itam/device.md

      - projects/django-template/itam/operating_system.md

      - projects/django-template/itam/software.md

    - projects/django-template/settings.md

    - Development:

      - projects/django-template/development/index.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

